# Generated by Django 5.1.2 on 2024-11-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
